// Google Places API Service
// Uses backend server when available, falls back to mock data

const API_KEY = import.meta.env.VITE_GOOGLE_PLACES_API_KEY;
// Use environment variable for backend URL, fallback to localhost for development
const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || 
  (import.meta.env.DEV ? 'http://localhost:3001' : '');

// Comprehensive temple database - 50 famous temples across India
const mockTemplesData = [
  // PUNJAB & NORTH
  {
    id: 1,
    name: "Golden Temple",
    hindiName: "हरमंदिर साहिब",
    location: "Amritsar, Punjab",
    state: "Punjab",
    deity: "Sikh Gurus",
    religion: "Sikhism",
    image: "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?w=800&h=600&fit=crop",
    description: "The holiest Gurdwara and the most important pilgrimage site of Sikhism. Features stunning gold-plated architecture and the sacred Amrit Sarovar pool.",
    timings: "Open 24 hours",
    bestTime: "October to March",
    dressCode: "Head covering required",
    coordinates: { lat: 31.6200, lng: 74.8765 },
    googleRating: 4.9,
  },
  {
    id: 2,
    name: "Vaishno Devi Temple",
    hindiName: "वैष्णो देवी मंदिर",
    location: "Katra, Jammu & Kashmir",
    state: "Jammu & Kashmir",
    deity: "Goddess Vaishno Devi",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=800&h=600&fit=crop",
    description: "One of the most revered Hindu temples dedicated to Shakti, located in the Trikuta Mountains. Requires a 13km trek to reach the holy cave shrine.",
    timings: "Open 24 hours (during yatra)",
    bestTime: "March to October",
    dressCode: "Comfortable warm clothing",
    coordinates: { lat: 33.0308, lng: 74.9490 },
    googleRating: 4.8,
  },
  {
    id: 3,
    name: "Jwalaji Temple",
    hindiName: "ज्वाला जी मंदिर",
    location: "Kangra, Himachal Pradesh",
    state: "Himachal Pradesh",
    deity: "Goddess Jwala",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1609766418204-94aae0ecb7c5?w=800&h=600&fit=crop",
    description: "Famous for its eternal flames that burn without any fuel. One of the 51 Shakti Peethas.",
    timings: "5:00 AM - 10:00 PM",
    bestTime: "March to June",
    dressCode: "Traditional attire",
    coordinates: { lat: 31.8684, lng: 76.3234 },
    googleRating: 4.6,
  },

  // UTTAR PRADESH & UTTARAKHAND
  {
    id: 4,
    name: "Kashi Vishwanath Temple",
    hindiName: "काशी विश्वनाथ मंदिर",
    location: "Varanasi, Uttar Pradesh",
    state: "Uttar Pradesh",
    deity: "Lord Shiva",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&h=600&fit=crop",
    description: "One of the most famous Hindu temples dedicated to Lord Shiva. One of the twelve Jyotirlingas, located on the banks of the sacred Ganges.",
    timings: "3:00 AM - 11:00 PM",
    bestTime: "October to March",
    dressCode: "Traditional attire",
    coordinates: { lat: 25.3109, lng: 83.0107 },
    googleRating: 4.7,
  },
  {
    id: 5,
    name: "Kedarnath Temple",
    hindiName: "केदारनाथ मंदिर",
    location: "Kedarnath, Uttarakhand",
    state: "Uttarakhand",
    deity: "Lord Shiva",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop",
    description: "One of the holiest Hindu temples dedicated to Lord Shiva, located at 3,583m in the Himalayas. Part of the Char Dham pilgrimage.",
    timings: "4:00 AM - 9:00 PM (May-October)",
    bestTime: "May to June, September to October",
    dressCode: "Warm traditional clothing",
    coordinates: { lat: 30.7352, lng: 79.0669 },
    googleRating: 4.9,
  },
  {
    id: 6,
    name: "Badrinath Temple",
    hindiName: "बद्रीनाथ मंदिर",
    location: "Badrinath, Uttarakhand",
    state: "Uttarakhand",
    deity: "Lord Vishnu",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&h=600&fit=crop",
    description: "One of the Char Dham pilgrimage sites dedicated to Lord Vishnu. Situated along the Alaknanda River at 3,133m elevation.",
    timings: "4:30 AM - 9:00 PM (Apr-Nov)",
    bestTime: "May to June, September to October",
    dressCode: "Warm clothing",
    coordinates: { lat: 30.7433, lng: 79.4938 },
    googleRating: 4.8,
  },
  {
    id: 7,
    name: "Gangotri Temple",
    hindiName: "गंगोत्री मंदिर",
    location: "Gangotri, Uttarakhand",
    state: "Uttarakhand",
    deity: "Goddess Ganga",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1544006659-f0b21884ce1d?w=800&h=600&fit=crop",
    description: "Sacred temple dedicated to Goddess Ganga at the origin of the Ganges River. Part of Char Dham.",
    timings: "6:00 AM - 9:00 PM (May-Oct)",
    bestTime: "May to October",
    dressCode: "Warm clothing",
    coordinates: { lat: 31.0011, lng: 78.9397 },
    googleRating: 4.7,
  },
  {
    id: 8,
    name: "Yamunotri Temple",
    hindiName: "यमुनोत्री मंदिर",
    location: "Yamunotri, Uttarakhand",
    state: "Uttarakhand",
    deity: "Goddess Yamuna",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1621427638887-f6f3c677e1c9?w=800&h=600&fit=crop",
    description: "Temple dedicated to Goddess Yamuna at the source of the Yamuna River. Part of Char Dham.",
    timings: "6:00 AM - 8:00 PM (May-Oct)",
    bestTime: "May to October",
    dressCode: "Warm clothing",
    coordinates: { lat: 31.0180, lng: 78.4640 },
    googleRating: 4.6,
  },
  {
    id: 9,
    name: "ISKCON Temple Vrindavan",
    hindiName: "इस्कॉन मंदिर वृंदावन",
    location: "Vrindavan, Uttar Pradesh",
    state: "Uttar Pradesh",
    deity: "Lord Krishna",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1585135497273-1a86b09fe70e?w=800&h=600&fit=crop",
    description: "Beautiful ISKCON temple in the holy land of Krishna. Features stunning architecture and spiritual atmosphere.",
    timings: "4:30 AM - 8:30 PM",
    bestTime: "October to March",
    dressCode: "Modest clothing",
    coordinates: { lat: 27.5833, lng: 77.6833 },
    googleRating: 4.7,
  },
  {
    id: 10,
    name: "Banke Bihari Temple",
    hindiName: "बांके बिहारी मंदिर",
    location: "Vrindavan, Uttar Pradesh",
    state: "Uttar Pradesh",
    deity: "Lord Krishna",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1567591370504-80a7bf0aef1d?w=800&h=600&fit=crop",
    description: "One of the most revered temples in Vrindavan dedicated to Lord Krishna in his Banke Bihari form.",
    timings: "7:45 AM - 12:00 PM, 5:30 PM - 9:30 PM",
    bestTime: "Holi festival",
    dressCode: "Traditional attire",
    coordinates: { lat: 27.5896, lng: 77.6590 },
    googleRating: 4.6,
  },

  // DELHI & RAJASTHAN
  {
    id: 11,
    name: "Akshardham Temple",
    hindiName: "अक्षरधाम मंदिर",
    location: "New Delhi, Delhi",
    state: "Delhi",
    deity: "Swaminarayan",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1585135497273-1a86b09fe70e?w=800&h=600&fit=crop",
    description: "A modern Hindu temple complex showcasing Indian culture, spirituality, and architecture. Features exhibitions, boat ride, and musical fountain.",
    timings: "9:30 AM - 6:30 PM (Closed Mondays)",
    bestTime: "October to March",
    dressCode: "Modest clothing",
    coordinates: { lat: 28.6127, lng: 77.2773 },
    googleRating: 4.7,
  },
  {
    id: 12,
    name: "Lotus Temple",
    hindiName: "लोटस टेम्पल",
    location: "New Delhi, Delhi",
    state: "Delhi",
    deity: "Bahá'í Faith",
    religion: "Bahá'í",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&h=600&fit=crop",
    description: "Bahá'í House of Worship known for its stunning lotus-shaped architecture. Open to all faiths for meditation.",
    timings: "9:00 AM - 5:30 PM (Closed Mondays)",
    bestTime: "October to March",
    dressCode: "Modest clothing",
    coordinates: { lat: 28.5535, lng: 77.2588 },
    googleRating: 4.5,
  },
  {
    id: 13,
    name: "Birla Mandir Delhi",
    hindiName: "बिड़ला मंदिर दिल्ली",
    location: "New Delhi, Delhi",
    state: "Delhi",
    deity: "Lord Vishnu & Lakshmi",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&h=600&fit=crop",
    description: "Also known as Laxminarayan Temple, built by the Birla family. Beautiful red sandstone architecture.",
    timings: "4:30 AM - 1:30 PM, 2:30 PM - 9:00 PM",
    bestTime: "Year round",
    dressCode: "Modest clothing",
    coordinates: { lat: 28.6324, lng: 77.1994 },
    googleRating: 4.5,
  },
  {
    id: 14,
    name: "Brahma Temple Pushkar",
    hindiName: "ब्रह्मा मंदिर पुष्कर",
    location: "Pushkar, Rajasthan",
    state: "Rajasthan",
    deity: "Lord Brahma",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=800&h=600&fit=crop",
    description: "One of very few temples in the world dedicated to Lord Brahma. Located on the shores of Pushkar Lake.",
    timings: "6:30 AM - 8:30 PM",
    bestTime: "November (Pushkar Fair)",
    dressCode: "Traditional attire",
    coordinates: { lat: 26.4898, lng: 74.5511 },
    googleRating: 4.4,
  },
  {
    id: 15,
    name: "Karni Mata Temple",
    hindiName: "करणी माता मंदिर",
    location: "Deshnoke, Rajasthan",
    state: "Rajasthan",
    deity: "Karni Mata",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1609766418204-94aae0ecb7c5?w=800&h=600&fit=crop",
    description: "Famous as the 'Rat Temple' where thousands of rats are considered sacred and worshipped.",
    timings: "4:00 AM - 10:00 PM",
    bestTime: "October to March",
    dressCode: "Remove footwear",
    coordinates: { lat: 27.7833, lng: 73.3333 },
    googleRating: 4.3,
  },

  // GUJARAT
  {
    id: 16,
    name: "Somnath Temple",
    hindiName: "सोमनाथ मंदिर",
    location: "Somnath, Gujarat",
    state: "Gujarat",
    deity: "Lord Shiva",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&h=600&fit=crop",
    description: "First among the twelve Jyotirlinga shrines of Shiva. Rebuilt multiple times, it stands majestically on the Arabian Sea coast.",
    timings: "6:00 AM - 9:00 PM",
    bestTime: "October to March",
    dressCode: "Traditional attire",
    coordinates: { lat: 20.8880, lng: 70.4012 },
    googleRating: 4.8,
  },
  {
    id: 17,
    name: "Dwarkadhish Temple",
    hindiName: "द्वारकाधीश मंदिर",
    location: "Dwarka, Gujarat",
    state: "Gujarat",
    deity: "Lord Krishna",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?w=800&h=600&fit=crop",
    description: "One of the Char Dham pilgrimage sites. The temple is believed to be over 2,500 years old.",
    timings: "6:30 AM - 1:00 PM, 5:00 PM - 9:30 PM",
    bestTime: "October to March",
    dressCode: "Traditional attire",
    coordinates: { lat: 22.2376, lng: 68.9674 },
    googleRating: 4.7,
  },
  {
    id: 18,
    name: "Akshardham Gandhinagar",
    hindiName: "अक्षरधाम गांधीनगर",
    location: "Gandhinagar, Gujarat",
    state: "Gujarat",
    deity: "Swaminarayan",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1585135497273-1a86b09fe70e?w=800&h=600&fit=crop",
    description: "Stunning pink sandstone temple complex dedicated to Swaminarayan. Features beautiful carvings and exhibitions.",
    timings: "9:30 AM - 7:30 PM (Closed Mondays)",
    bestTime: "October to March",
    dressCode: "Modest clothing",
    coordinates: { lat: 23.2072, lng: 72.6557 },
    googleRating: 4.8,
  },
  {
    id: 19,
    name: "Ambaji Temple",
    hindiName: "अंबाजी मंदिर",
    location: "Ambaji, Gujarat",
    state: "Gujarat",
    deity: "Goddess Amba",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1567591370504-80a7bf0aef1d?w=800&h=600&fit=crop",
    description: "One of the 51 Shakti Peethas, dedicated to Goddess Amba. Popular pilgrimage site.",
    timings: "7:00 AM - 12:00 PM, 4:00 PM - 9:00 PM",
    bestTime: "Navratri",
    dressCode: "Traditional attire",
    coordinates: { lat: 24.3313, lng: 72.8499 },
    googleRating: 4.5,
  },

  // MAHARASHTRA
  {
    id: 20,
    name: "Siddhivinayak Temple",
    hindiName: "सिद्धिविनायक मंदिर",
    location: "Mumbai, Maharashtra",
    state: "Maharashtra",
    deity: "Lord Ganesha",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1567591370504-80a7bf0aef1d?w=800&h=600&fit=crop",
    description: "One of the richest and most visited Ganesha temples in Mumbai. Famous for granting wishes to devotees.",
    timings: "5:30 AM - 10:00 PM",
    bestTime: "Ganesh Chaturthi",
    dressCode: "Modest clothing",
    coordinates: { lat: 19.0169, lng: 72.8306 },
    googleRating: 4.6,
  },
  {
    id: 21,
    name: "Shirdi Sai Baba Temple",
    hindiName: "शिरडी साईं बाबा मंदिर",
    location: "Shirdi, Maharashtra",
    state: "Maharashtra",
    deity: "Sai Baba",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=800&h=600&fit=crop",
    description: "The most famous Sai Baba temple where he lived and attained Samadhi. Visited by millions annually.",
    timings: "4:00 AM - 11:00 PM",
    bestTime: "Year round",
    dressCode: "Modest clothing",
    coordinates: { lat: 19.7667, lng: 74.4833 },
    googleRating: 4.8,
  },
  {
    id: 22,
    name: "Trimbakeshwar Temple",
    hindiName: "त्र्यंबकेश्वर मंदिर",
    location: "Trimbak, Maharashtra",
    state: "Maharashtra",
    deity: "Lord Shiva",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&h=600&fit=crop",
    description: "One of the twelve Jyotirlingas. Located at the source of the Godavari River.",
    timings: "5:30 AM - 9:00 PM",
    bestTime: "Monsoon",
    dressCode: "Traditional attire",
    coordinates: { lat: 19.9322, lng: 73.5308 },
    googleRating: 4.6,
  },
  {
    id: 23,
    name: "Ashtavinayak Temples",
    hindiName: "अष्टविनायक मंदिर",
    location: "Pune Region, Maharashtra",
    state: "Maharashtra",
    deity: "Lord Ganesha",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&h=600&fit=crop",
    description: "Circuit of 8 ancient Ganesha temples around Pune. Each temple has unique significance.",
    timings: "5:00 AM - 10:00 PM",
    bestTime: "Ganesh Chaturthi",
    dressCode: "Traditional attire",
    coordinates: { lat: 18.5204, lng: 73.8567 },
    googleRating: 4.7,
  },
  {
    id: 24,
    name: "Mahalakshmi Temple Mumbai",
    hindiName: "महालक्ष्मी मंदिर मुंबई",
    location: "Mumbai, Maharashtra",
    state: "Maharashtra",
    deity: "Goddess Lakshmi",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1544006659-f0b21884ce1d?w=800&h=600&fit=crop",
    description: "One of the most famous temples in Mumbai dedicated to Goddess Lakshmi. Located near the Arabian Sea.",
    timings: "6:00 AM - 10:00 PM",
    bestTime: "Navratri",
    dressCode: "Traditional attire",
    coordinates: { lat: 18.9775, lng: 72.8090 },
    googleRating: 4.5,
  },

  // SOUTH INDIA - TAMIL NADU
  {
    id: 25,
    name: "Meenakshi Temple",
    hindiName: "मीनाक्षी मंदिर",
    location: "Madurai, Tamil Nadu",
    state: "Tamil Nadu",
    deity: "Goddess Meenakshi",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&h=600&fit=crop",
    description: "Historic Dravidian temple with 14 stunning gopurams, 33,000 sculptures, and the sacred temple tank.",
    timings: "5:00 AM - 12:30 PM, 4:00 PM - 10:00 PM",
    bestTime: "January-February (Float Festival)",
    dressCode: "Traditional attire preferred",
    coordinates: { lat: 9.9195, lng: 78.1193 },
    googleRating: 4.7,
  },
  {
    id: 26,
    name: "Brihadeeswarar Temple",
    hindiName: "बृहदेश्वर मंदिर",
    location: "Thanjavur, Tamil Nadu",
    state: "Tamil Nadu",
    deity: "Lord Shiva",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1621427638887-f6f3c677e1c9?w=800&h=600&fit=crop",
    description: "UNESCO World Heritage Site built by Raja Raja Chola I. Features a 216-foot vimana and a massive Nandi statue.",
    timings: "6:00 AM - 12:30 PM, 4:00 PM - 8:30 PM",
    bestTime: "October to March",
    dressCode: "Traditional attire",
    coordinates: { lat: 10.7828, lng: 79.1318 },
    googleRating: 4.8,
  },
  {
    id: 27,
    name: "Ramanathaswamy Temple",
    hindiName: "रामनाथस्वामी मंदिर",
    location: "Rameswaram, Tamil Nadu",
    state: "Tamil Nadu",
    deity: "Lord Shiva",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop",
    description: "One of the Char Dham sites with the longest temple corridor in India. Features 22 sacred wells.",
    timings: "5:00 AM - 1:00 PM, 3:00 PM - 9:00 PM",
    bestTime: "October to April",
    dressCode: "Traditional attire",
    coordinates: { lat: 9.2885, lng: 79.3173 },
    googleRating: 4.7,
  },
  {
    id: 28,
    name: "Kapaleeshwarar Temple",
    hindiName: "कपालीश्वर मंदिर",
    location: "Chennai, Tamil Nadu",
    state: "Tamil Nadu",
    deity: "Lord Shiva",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&h=600&fit=crop",
    description: "Beautiful Dravidian temple in Mylapore with stunning gopuram. Over 1,300 years old.",
    timings: "5:30 AM - 12:00 PM, 4:00 PM - 9:00 PM",
    bestTime: "March-April (Panguni festival)",
    dressCode: "Traditional attire",
    coordinates: { lat: 13.0336, lng: 80.2697 },
    googleRating: 4.6,
  },
  {
    id: 29,
    name: "Nataraja Temple Chidambaram",
    hindiName: "नटराज मंदिर चिदंबरम",
    location: "Chidambaram, Tamil Nadu",
    state: "Tamil Nadu",
    deity: "Lord Shiva (Nataraja)",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&h=600&fit=crop",
    description: "Famous for the cosmic dance of Shiva as Nataraja. One of the Pancha Bhoota Stalas.",
    timings: "6:00 AM - 12:00 PM, 4:00 PM - 10:00 PM",
    bestTime: "December-January",
    dressCode: "Traditional attire",
    coordinates: { lat: 11.3992, lng: 79.6941 },
    googleRating: 4.7,
  },

  // ANDHRA PRADESH & TELANGANA
  {
    id: 30,
    name: "Tirupati Balaji",
    hindiName: "तिरुपति बालाजी",
    location: "Tirupati, Andhra Pradesh",
    state: "Andhra Pradesh",
    deity: "Lord Venkateswara",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1544006659-f0b21884ce1d?w=800&h=600&fit=crop",
    description: "The richest and most visited temple in the world. Dedicated to Lord Venkateswara on the seven hills of Tirumala.",
    timings: "3:00 AM - 12:00 AM",
    bestTime: "September to February",
    dressCode: "Traditional Hindu attire",
    coordinates: { lat: 13.6833, lng: 79.3472 },
    googleRating: 4.8,
  },
  {
    id: 31,
    name: "Simhachalam Temple",
    hindiName: "सिंहाचलम मंदिर",
    location: "Visakhapatnam, Andhra Pradesh",
    state: "Andhra Pradesh",
    deity: "Lord Narasimha",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1585135497273-1a86b09fe70e?w=800&h=600&fit=crop",
    description: "Ancient temple dedicated to Lord Narasimha. Features unique Chandana Yatra festival.",
    timings: "6:00 AM - 8:30 PM",
    bestTime: "April-May",
    dressCode: "Traditional attire",
    coordinates: { lat: 17.7667, lng: 83.2500 },
    googleRating: 4.6,
  },
  {
    id: 32,
    name: "Yadadri Temple",
    hindiName: "यादाद्री मंदिर",
    location: "Yadagirigutta, Telangana",
    state: "Telangana",
    deity: "Lord Narasimha",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1567591370504-80a7bf0aef1d?w=800&h=600&fit=crop",
    description: "Recently renovated magnificent temple dedicated to Lord Narasimha. Stunning white marble architecture.",
    timings: "4:30 AM - 9:00 PM",
    bestTime: "Year round",
    dressCode: "Traditional attire",
    coordinates: { lat: 17.5977, lng: 78.9493 },
    googleRating: 4.7,
  },
  {
    id: 33,
    name: "Birla Mandir Hyderabad",
    hindiName: "बिड़ला मंदिर हैदराबाद",
    location: "Hyderabad, Telangana",
    state: "Telangana",
    deity: "Lord Venkateswara",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&h=600&fit=crop",
    description: "Beautiful white marble temple built on a hillock. Offers panoramic views of Hyderabad.",
    timings: "7:00 AM - 12:00 PM, 3:00 PM - 9:00 PM",
    bestTime: "Year round",
    dressCode: "Modest clothing",
    coordinates: { lat: 17.4063, lng: 78.4691 },
    googleRating: 4.5,
  },

  // KARNATAKA
  {
    id: 34,
    name: "Virupaksha Temple",
    hindiName: "विरुपाक्ष मंदिर",
    location: "Hampi, Karnataka",
    state: "Karnataka",
    deity: "Lord Shiva",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop",
    description: "UNESCO World Heritage Site in the ruins of Vijayanagara Empire. Stunning 7th-century temple.",
    timings: "6:00 AM - 6:00 PM",
    bestTime: "October to March",
    dressCode: "Modest clothing",
    coordinates: { lat: 15.3350, lng: 76.4600 },
    googleRating: 4.7,
  },
  {
    id: 35,
    name: "Murudeshwar Temple",
    hindiName: "मुरुडेश्वर मंदिर",
    location: "Murudeshwar, Karnataka",
    state: "Karnataka",
    deity: "Lord Shiva",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&h=600&fit=crop",
    description: "Features the world's second tallest Shiva statue (123 ft). Located on the Arabian Sea coast.",
    timings: "6:00 AM - 8:30 PM",
    bestTime: "October to February",
    dressCode: "Modest clothing",
    coordinates: { lat: 14.0943, lng: 74.4847 },
    googleRating: 4.6,
  },
  {
    id: 36,
    name: "Dharmasthala Temple",
    hindiName: "धर्मस्थल मंदिर",
    location: "Dharmasthala, Karnataka",
    state: "Karnataka",
    deity: "Lord Manjunatha (Shiva)",
    religion: "Hinduism/Jainism",
    image: "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?w=800&h=600&fit=crop",
    description: "Unique temple administered by Jain priests where Hindu deity is worshipped. Famous for free meals.",
    timings: "6:30 AM - 2:00 PM, 5:00 PM - 8:30 PM",
    bestTime: "November-February",
    dressCode: "Traditional attire",
    coordinates: { lat: 12.9513, lng: 75.3725 },
    googleRating: 4.8,
  },
  {
    id: 37,
    name: "Kukke Subramanya Temple",
    hindiName: "कुक्के सुब्रमण्य मंदिर",
    location: "Subramanya, Karnataka",
    state: "Karnataka",
    deity: "Lord Subramanya",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&h=600&fit=crop",
    description: "Famous temple for Sarpa Dosha Nivarana (snake curse removal). Located in the Western Ghats.",
    timings: "6:00 AM - 9:00 PM",
    bestTime: "November to February",
    dressCode: "Traditional attire",
    coordinates: { lat: 12.6753, lng: 75.6281 },
    googleRating: 4.6,
  },

  // KERALA
  {
    id: 38,
    name: "Guruvayur Temple",
    hindiName: "गुरुवायूर मंदिर",
    location: "Guruvayur, Kerala",
    state: "Kerala",
    deity: "Lord Krishna",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1544006659-f0b21884ce1d?w=800&h=600&fit=crop",
    description: "One of the most important Krishna temples in India. Known as 'Dwarka of the South'.",
    timings: "3:00 AM - 1:00 PM, 4:30 PM - 10:00 PM",
    bestTime: "February-March",
    dressCode: "Traditional Kerala attire (men: mundu)",
    coordinates: { lat: 10.5940, lng: 76.0408 },
    googleRating: 4.7,
  },
  {
    id: 39,
    name: "Sabarimala Temple",
    hindiName: "सबरीमाला मंदिर",
    location: "Pathanamthitta, Kerala",
    state: "Kerala",
    deity: "Lord Ayyappa",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop",
    description: "One of the largest annual pilgrimages in the world. Requires 41-day vratham before visit.",
    timings: "4:00 AM - 11:00 PM (during season)",
    bestTime: "November to January",
    dressCode: "Black/Blue dhoti, 41-day vratham required",
    coordinates: { lat: 9.4353, lng: 77.0808 },
    googleRating: 4.9,
  },
  {
    id: 40,
    name: "Padmanabhaswamy Temple",
    hindiName: "पद्मनाभस्वामी मंदिर",
    location: "Thiruvananthapuram, Kerala",
    state: "Kerala",
    deity: "Lord Vishnu",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1585135497273-1a86b09fe70e?w=800&h=600&fit=crop",
    description: "One of the richest temples in the world. Features Lord Vishnu in Anantha Shayana posture.",
    timings: "3:30 AM - 12:00 PM, 5:00 PM - 8:00 PM",
    bestTime: "October to March",
    dressCode: "Traditional Kerala attire (men: mundu)",
    coordinates: { lat: 8.4829, lng: 76.9438 },
    googleRating: 4.7,
  },
  {
    id: 41,
    name: "Attukal Bhagavathy Temple",
    hindiName: "अट्टुकल भगवती मंदिर",
    location: "Thiruvananthapuram, Kerala",
    state: "Kerala",
    deity: "Goddess Bhagavathy",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1567591370504-80a7bf0aef1d?w=800&h=600&fit=crop",
    description: "Holds Guinness Record for largest gathering of women. Famous for Pongala festival.",
    timings: "5:00 AM - 12:00 PM, 5:00 PM - 8:00 PM",
    bestTime: "February-March (Pongala)",
    dressCode: "Traditional attire",
    coordinates: { lat: 8.4855, lng: 76.9515 },
    googleRating: 4.6,
  },

  // ODISHA & EAST INDIA
  {
    id: 42,
    name: "Jagannath Temple",
    hindiName: "जगन्नाथ मंदिर",
    location: "Puri, Odisha",
    state: "Odisha",
    deity: "Lord Jagannath",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1621427638887-f6f3c677e1c9?w=800&h=600&fit=crop",
    description: "One of the Char Dham sites. Famous for the annual Rath Yatra and Mahaprasad.",
    timings: "5:00 AM - 11:00 PM",
    bestTime: "June-July (Rath Yatra)",
    dressCode: "Traditional attire",
    coordinates: { lat: 19.8048, lng: 85.8181 },
    googleRating: 4.6,
  },
  {
    id: 43,
    name: "Konark Sun Temple",
    hindiName: "कोणार्क सूर्य मंदिर",
    location: "Konark, Odisha",
    state: "Odisha",
    deity: "Sun God",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&h=600&fit=crop",
    description: "UNESCO World Heritage Site. 13th-century temple designed as a massive chariot with 24 wheels.",
    timings: "6:00 AM - 8:00 PM",
    bestTime: "October to March",
    dressCode: "Modest clothing",
    coordinates: { lat: 19.8876, lng: 86.0945 },
    googleRating: 4.7,
  },
  {
    id: 44,
    name: "Lingaraj Temple",
    hindiName: "लिंगराज मंदिर",
    location: "Bhubaneswar, Odisha",
    state: "Odisha",
    deity: "Lord Shiva",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&h=600&fit=crop",
    description: "The largest temple in Bhubaneswar. Magnificent example of Kalinga architecture.",
    timings: "5:00 AM - 9:00 PM",
    bestTime: "February (Shivaratri)",
    dressCode: "Traditional attire",
    coordinates: { lat: 20.2381, lng: 85.8338 },
    googleRating: 4.6,
  },
  {
    id: 45,
    name: "Dakshineswar Kali Temple",
    hindiName: "दक्षिणेश्वर काली मंदिर",
    location: "Kolkata, West Bengal",
    state: "West Bengal",
    deity: "Goddess Kali",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=800&h=600&fit=crop",
    description: "Famous temple where Sri Ramakrishna attained spiritual vision. Located on the Hooghly River.",
    timings: "6:00 AM - 12:30 PM, 3:00 PM - 8:30 PM",
    bestTime: "October (Durga Puja)",
    dressCode: "Modest clothing",
    coordinates: { lat: 22.6548, lng: 88.3578 },
    googleRating: 4.7,
  },
  {
    id: 46,
    name: "Kalighat Kali Temple",
    hindiName: "कालीघाट काली मंदिर",
    location: "Kolkata, West Bengal",
    state: "West Bengal",
    deity: "Goddess Kali",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1567591370504-80a7bf0aef1d?w=800&h=600&fit=crop",
    description: "One of the 51 Shakti Peethas. Ancient temple from which Calcutta derived its name.",
    timings: "5:00 AM - 2:00 PM, 5:00 PM - 10:30 PM",
    bestTime: "October (Durga Puja)",
    dressCode: "Modest clothing",
    coordinates: { lat: 22.5197, lng: 88.3426 },
    googleRating: 4.4,
  },

  // MADHYA PRADESH & CENTRAL INDIA
  {
    id: 47,
    name: "Mahakaleshwar Temple",
    hindiName: "महाकालेश्वर मंदिर",
    location: "Ujjain, Madhya Pradesh",
    state: "Madhya Pradesh",
    deity: "Lord Shiva",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop",
    description: "One of the twelve Jyotirlingas. Famous for the Bhasma Aarti performed with sacred ash.",
    timings: "4:00 AM - 11:00 PM",
    bestTime: "Year round",
    dressCode: "Traditional attire",
    coordinates: { lat: 23.1828, lng: 75.7682 },
    googleRating: 4.7,
  },
  {
    id: 48,
    name: "Khajuraho Temples",
    hindiName: "खजुराहो मंदिर",
    location: "Khajuraho, Madhya Pradesh",
    state: "Madhya Pradesh",
    deity: "Various Hindu & Jain deities",
    religion: "Hinduism/Jainism",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&h=600&fit=crop",
    description: "UNESCO World Heritage Site. Famous for stunning erotic sculptures and Nagara architecture.",
    timings: "Sunrise to Sunset",
    bestTime: "October to February",
    dressCode: "Modest clothing",
    coordinates: { lat: 24.8318, lng: 79.9199 },
    googleRating: 4.6,
  },
  {
    id: 49,
    name: "Omkareshwar Temple",
    hindiName: "ओंकारेश्वर मंदिर",
    location: "Omkareshwar, Madhya Pradesh",
    state: "Madhya Pradesh",
    deity: "Lord Shiva",
    religion: "Hinduism",
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&h=600&fit=crop",
    description: "One of the twelve Jyotirlingas on an island shaped like Om in the Narmada River.",
    timings: "5:00 AM - 10:00 PM",
    bestTime: "Year round",
    dressCode: "Traditional attire",
    coordinates: { lat: 22.2448, lng: 76.1516 },
    googleRating: 4.6,
  },
  {
    id: 50,
    name: "Sanchi Stupa",
    hindiName: "सांची स्तूप",
    location: "Sanchi, Madhya Pradesh",
    state: "Madhya Pradesh",
    deity: "Buddha",
    religion: "Buddhism",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&h=600&fit=crop",
    description: "UNESCO World Heritage Site. Oldest stone structures in India, built by Emperor Ashoka.",
    timings: "8:30 AM - 5:00 PM",
    bestTime: "October to March",
    dressCode: "Modest clothing",
    coordinates: { lat: 23.4793, lng: 77.7396 },
    googleRating: 4.5,
  },
];

// Simulate network delay
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * Search for temples
 * Uses backend when available, falls back to mock data
 */
export async function searchTemples(query = '', location = null) {
  console.log('🔍 Searching temples...', { query, location });
  
  // Try backend first
  try {
    const params = new URLSearchParams();
    if (query) params.set('query', query);
    if (location) {
      params.set('lat', location.lat);
      params.set('lng', location.lng);
    }
    
    const response = await fetch(`${BACKEND_URL}/api/temples?${params}`, {
      signal: AbortSignal.timeout(5000) // 5 second timeout
    });
    
    if (response.ok) {
      const data = await response.json();
      console.log('✅ Got temples from backend:', data.length);
      return data;
    }
  } catch (err) {
    console.log('⚠️ Backend unavailable, using mock data');
  }
  
  // Fall back to mock data
  await delay(600);
  
  let results = [...mockTemplesData];
  
  // Filter by query
  if (query) {
    const q = query.toLowerCase();
    results = results.filter(t => 
      t.name.toLowerCase().includes(q) ||
      t.location.toLowerCase().includes(q) ||
      t.deity.toLowerCase().includes(q) ||
      t.state.toLowerCase().includes(q) ||
      (t.hindiName && t.hindiName.includes(q))
    );
  }
  
  console.log(`✅ Found ${results.length} temples (mock data)`);
  
  return results.map(t => ({
    ...t,
    isWishlisted: false,
    isVisited: false,
    friendRatings: [],
  }));
}

/**
 * Get details for a specific temple
 */
export async function getTempleDetails(templeId) {
  console.log('📍 Getting temple details...', { templeId });
  
  // Try backend first
  try {
    const response = await fetch(`${BACKEND_URL}/api/temples/${templeId}`, {
      signal: AbortSignal.timeout(5000)
    });
    
    if (response.ok) {
      return await response.json();
    }
  } catch (err) {
    console.log('⚠️ Backend unavailable, using mock data');
  }
  
  // Fall back to mock data
  await delay(400);
  
  const temple = mockTemplesData.find(t => t.id === templeId || t.id === parseInt(templeId));
  if (!temple) throw new Error('Temple not found');
  
  return {
    ...temple,
    isWishlisted: false,
    isVisited: false,
    friendRatings: [],
  };
}

export default {
  searchTemples,
  getTempleDetails,
  TEMPLE_COUNT: mockTemplesData.length,
};
